In [1]:
import numpy as np

In [18]:
x = np.arange(10.0)
print(x, type(x))
xl = np.array_split(x, 5)
print(type(xl[0]))
xd = np.delete(xl, np.array([1,3]), axis = 1)
print xd
xt = xl[[1,3]]
print xtJJ

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]), <type 'numpy.ndarray'>)
<type 'numpy.ndarray'>
[[ 0.]
 [ 2.]
 [ 4.]
 [ 6.]
 [ 8.]]


TypeError: list indices must be integers, not list

In [19]:
  def euclidean_distance(x1, x2):
    """
      Compute the Euclidean distance of two vectors

      Inputs:
        Two numpy array of shape (D, 1)

      Return:
        The Euclidean distance of two vectors
    """
    return np.sqrt(np.sum(np.square(x1-x2)))

In [10]:
print euclidean_distance(a, b)

1.73205080757


In [65]:
counts = np.zeros((3,4))
x  = np.arange(-1, 11, 1).reshape(3, 4)
counts[x>0] = 1
print x
print counts

y = [2,0,3]

counts[range(x.shape[0]), ind] = -np.sum(counts, axis = 1)
print counts

x[range(x.shape[0]), ind] = np.array(ind)
print x

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]
[[ 0.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0. -2.  1.  1.]
 [-4.  1.  1.  1.]
 [ 1.  1.  1. -4.]]
[[-1  1  1  2]
 [ 0  4  5  6]
 [ 7  8  9  3]]


In [68]:
x = np.random.randn(5, 6)
sub = x[range(5), [3, 4, 2, 1, 3]]
print x
print sub

sub = sub - sub
print x
print sub

[[-0.01316434 -0.42915331  0.2655063   0.37970945  0.93661385 -1.93940255]
 [ 0.12591192 -1.5363093  -0.72346865  0.97366488  0.30114682 -0.93830271]
 [ 0.76682179 -0.35442487  0.64640027 -0.38476636  1.45727355  3.01229262]
 [-0.22069972  1.14876028 -0.8716167  -2.14520302  1.11720326 -0.61339555]
 [ 0.20711121  0.339365   -2.0802548  -1.66263941  1.25352246  0.98599807]]
[ 0.37970945  0.30114682  0.64640027  1.14876028 -1.66263941]
[[-0.01316434 -0.42915331  0.2655063   0.37970945  0.93661385 -1.93940255]
 [ 0.12591192 -1.5363093  -0.72346865  0.97366488  0.30114682 -0.93830271]
 [ 0.76682179 -0.35442487  0.64640027 -0.38476636  1.45727355  3.01229262]
 [-0.22069972  1.14876028 -0.8716167  -2.14520302  1.11720326 -0.61339555]
 [ 0.20711121  0.339365   -2.0802548  -1.66263941  1.25352246  0.98599807]]
[ 0.  0.  0.  0.  0.]


In [70]:
y = x
print x
print y
y = y - y / 2
print x
print y

[[-0.01316434 -0.42915331  0.2655063   0.37970945  0.93661385 -1.93940255]
 [ 0.12591192 -1.5363093  -0.72346865  0.97366488  0.30114682 -0.93830271]
 [ 0.76682179 -0.35442487  0.64640027 -0.38476636  1.45727355  3.01229262]
 [-0.22069972  1.14876028 -0.8716167  -2.14520302  1.11720326 -0.61339555]
 [ 0.20711121  0.339365   -2.0802548  -1.66263941  1.25352246  0.98599807]]
[[-0.01316434 -0.42915331  0.2655063   0.37970945  0.93661385 -1.93940255]
 [ 0.12591192 -1.5363093  -0.72346865  0.97366488  0.30114682 -0.93830271]
 [ 0.76682179 -0.35442487  0.64640027 -0.38476636  1.45727355  3.01229262]
 [-0.22069972  1.14876028 -0.8716167  -2.14520302  1.11720326 -0.61339555]
 [ 0.20711121  0.339365   -2.0802548  -1.66263941  1.25352246  0.98599807]]
[[-0.01316434 -0.42915331  0.2655063   0.37970945  0.93661385 -1.93940255]
 [ 0.12591192 -1.5363093  -0.72346865  0.97366488  0.30114682 -0.93830271]
 [ 0.76682179 -0.35442487  0.64640027 -0.38476636  1.45727355  3.01229262]
 [-0.22069972  1.148760