In [1]:
import numpy as np

In [18]:
x = np.arange(10.0)
print(x, type(x))
xl = np.array_split(x, 5)
print(type(xl[0]))
xd = np.delete(xl, np.array([1,3]), axis = 1)
print xd
xt = xl[[1,3]]
print xtJJ

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]), <type 'numpy.ndarray'>)
<type 'numpy.ndarray'>
[[ 0.]
 [ 2.]
 [ 4.]
 [ 6.]
 [ 8.]]


TypeError: list indices must be integers, not list

In [19]:
  def euclidean_distance(x1, x2):
    """
      Compute the Euclidean distance of two vectors

      Inputs:
        Two numpy array of shape (D, 1)

      Return:
        The Euclidean distance of two vectors
    """
    return np.sqrt(np.sum(np.square(x1-x2)))

In [10]:
print euclidean_distance(a, b)

1.73205080757


In [65]:
counts = np.zeros((3,4))
x  = np.arange(-1, 11, 1).reshape(3, 4)
counts[x>0] = 1
print x
print counts

y = [2,0,3]

counts[range(x.shape[0]), ind] = -np.sum(counts, axis = 1)
print counts

x[range(x.shape[0]), ind] = np.array(ind)
print x

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]
[[ 0.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0. -2.  1.  1.]
 [-4.  1.  1.  1.]
 [ 1.  1.  1. -4.]]
[[-1  1  1  2]
 [ 0  4  5  6]
 [ 7  8  9  3]]


In [93]:
a = [1,2]
for i in np.arange(a[0], a[1], 0.2):
    print i
print 5e4

1.0
1.2
1.4
1.6
1.8
50000.0


In [85]:
x  = np.arange(24).reshape(2, 3, 4)
print x
print('')
print np.sum(x, axis = 0)
print('')
print np.sum(x, axis = 1)
print('')
print np.sum(x, axis = 2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[12 15 18 21]
 [48 51 54 57]]

[[ 6 22 38]
 [54 70 86]]


In [138]:
import operator
dic = {(1,2):(9,6), (3,4):(8,9)}
print list(dic.iterkeys())

#a = max(dic.iteritems(), kk=operator.itemgetter(1), key=kk[1])
#print a

stats = {'a':1000, 'b':3000, 'c': 100}
y = max(stats.iteritems(), key=lambda k: stats[k])
print y

[(1, 2), (3, 4)]


KeyError: ('a', 1000)

In [136]:
import operator
stats = {'a':1000, 'b':3000, 'c': 100}
max(stats.iteritems(), key=operator.itemgetter(1))[0]
stats = {'a':1000, 'b':3000, 'c': 100}
max(stats.iteritems(), key=lambda k: stats[k])


KeyError: ('a', 1000)